commands: dict[str, list[str]] = {
    'bot_name': [
        'cosmo',
        'cosmos'
    ],
    'nome' : [
        'livro',
        'procurando livro',
        'procurando por livro',
        'procurando por um livro',
        'procurando pelo livro',
        'procura livro',
        'procura um livro',
        'procura por um livro',
        'procura o livro',
        'procura pelo livro',
        'procure um livro',
        'procure o livro',
        'procuro um livro',
        'pesquisar um livro',
        'pesquisar livro',
        'pesquisar o livro',
        'procuro o livro',
        'encontre o livro',
        'encontre um livro',
        'quero o livro',
        'quero um livro',
    ],
    'edição' : [
        'edição',
        'procurando edição',
        'procurando por edição',
        'procurando por uma edição',
        'procurando pela edição',
        'procura edição',
        'procura por edição',
        'procura por uma edição',
        'procura uma edição',
        'procura a edição',
        'procura pela edição',
        'procure uma edição',
        'procure a edição',
        'procuro uma edição',
        'procuro a edição',
        'pesquisar a edição',
        'pesquisar por edição',
        'pesquisar por um edição',
        'pesquisar edição',
        'encontre a edição',
        'encontre uma edição',
        'quero a edição',
        'quero uma edição',
    ]
}